databases:
  - name: DB1
    host: arkaid-postgres.crcw0q6uux8e.ap-south-1.rds.amazonaws.com
    port: "5432"
    dbname: postgres
    username: postgres
    password: postgres
  - name: DB2
    host: dakshdb.crcw0q6uux8e.ap-south-1.rds.amazonaws.com
    port: "5432"
    dbname: postgres
    username: dakshdb
    password: dakshdb123
  - name: DB3
    host: centeralized-db.crcw0q6uux8e.ap-south-1.rds.amazonaws.com
    port: "5432"
    dbname: postgres
    username: sameer123
    password: ?k$+M40waa1mWrs%BYtw3aorf#l3
