databases:
- name: DB1
  host: dakshdb.crcw0q6uux8e.ap-south-1.rds.amazonaws.com
  port: '5432'
  dbname: postgres
  username: dakshdb
  password: dakshdb123
  tables:
  - name: epic_games
    columns:
      game_id: integer
      name: text
      game_slug: text
      price: double precision
      release_date: date
      platform: text
      description: text
      developer: text
      publisher: text
      genres: text
      average_hours_played: double precision
    type: table
  - name: epic_players
    columns:
      id: text
      name: text
      username: text
      age: integer
      dob: date
      email: text
      phone: text
      library: text
      favorites: text
      payment_method: text
      country: text
      total_hrs_played: double precision
      avg_rating_given: double precision
    type: table
  - name: developers
    columns:
      developer_id: integer
      developer: text
      active: boolean
      city: text
      country: text
      est: date
      notable_games: text
      notes: text
    type: table
  - name: publishers
    columns:
      publisher_id: integer
      publisher: text
      headquarters: text
      est: date
      notable_games_published: text
      notes: text
      active: boolean
    type: table
- name: DB2
  host: arkaid-postgres.crcw0q6uux8e.ap-south-1.rds.amazonaws.com
  port: '5432'
  dbname: postgres
  username: postgres
  password: postgres
  tables:
  - name: steam_games
    columns:
      id: text
      name: text
      release_date: date
      estimated_owners: text
      peak_ccu: text
      age_rating: text
      price: double precision
      dlc_count: integer
      about_the_game: text
      supported_languages: text
      full_audio_languages: text
      reviews: text
      header_image: text
      website: text
      support_url: text
      support_email: text
      windows: text
      mac: text
      linux: text
      achievements: integer
      average_hours_played: double precision
      developers: text
      publishers: text
      categories: text
      genres: text
      tags: text
      screenshots: text
      movies: text
    type: table
  - name: content_creators
    columns:
      id: text
      name: text
      country: text
      type_of_content: text
      average_views: integer
      revenue: double precision
      primary_game: text
    type: table
  - name: steam_players
    columns:
      id: text
      name: text
      username: text
      age: integer
      dob: date
      email: text
      phone: text
      library: text
      favorites: text
      payment_method: text
      country: text
      total_hrs_played: double precision
      avg_rating_given: double precision
    type: table
  - name: modders
    columns:
      id: text
      name: text
      type_of_mod: text
      country: text
      primary_game: text
    type: table
- name: DB3
  host: centeralized-db.crcw0q6uux8e.ap-south-1.rds.amazonaws.com
  port: '5432'
  dbname: postgres
  username: sameer123
  password: ?k$+M40waa1mWrs%BYtw3aorf#l3
  tables:
  - name: mv_epic_player_game_library
    columns:
      player_id: text
      game_id: text
      original_game_name: text
      matched_game_name: text
      match_score: double precision
    type: materialized_view
  - name: mv_player_game_map
    columns:
      player_id: text
      game_id: text
      platform: text
    type: materialized_view
  - name: mv_players
    columns:
      player_id: uuid
      player_name: text
      player_username: text
      player_email: text
      player_age: integer
      player_dob: date
      player_phone: text
      player_total_hrs_played: numeric(10,2)
      player_library_count: integer
      player_avg_rating_given: numeric(10,2)
      player_country: text
      player_platform: text
    type: materialized_view
  - name: mv_cc_games
    columns:
      creator_id: text
      creator_name: text
      content_type: text
      creator_country: text
      total_revenue_generated: double precision
      average_views: integer
      primary_game_id: uuid
      primary_game_name: text
      developer: text
      publisher: text
    type: materialized_view
  - name: mv_steam_player_game_library
    columns:
      player_id: text
      game_id: uuid
      original_game_name: text
      matched_game_name: text
      match_score: double precision
    type: materialized_view
  - name: mv_games
    columns:
      game_id: uuid
      game_name: text
      game_release_date: date
      game_price: numeric(10,2)
      game_developers: text
      game_publishers: text
      game_genres: text
      game_platform: text
    type: materialized_view
  - name: mv_game_content_region
    columns:
      game_id: uuid
      game_name: text
      game_genres: text
      modder_ids: text[]
      modder_name: text[]
      mod_type: text[]
      modder_country: text[]
      content_creator_id: text[]
      content_creator_name: text[]
      content_creator_country: text[]
      total_revenue_generated: double precision[]
      avg_views: integer[]
    type: materialized_view
