databases:
  - name: DB1
    host: dakshdb.crcw0q6uux8e.ap-south-1.rds.amazonaws.com
    port: "5432"
    dbname: postgres
    username: dakshdb
    password: dakshdb123
    tables:
      - name: epic_games
        columns:
          game_id: integer
          price: double precision
          release_date: date
          average_hours_played: double precision
          genres: text
          platform: text
          description: text
          developer: text
          name: text
          game_slug: text
          publisher: text
      - name: epic_players
        columns:
          age: integer
          dob: date
          total_hrs_played: double precision
          avg_rating_given: double precision
          id: text
          library: text
          favorites: text
          payment_method: text
          country: text
          phone: text
          name: text
          username: text
          email: text
      - name: developers
        columns:
          est: date
          active: boolean
          developer_id: integer
          country: text
          notable_games: text
          notes: text
          developer: text
          city: text
      - name: publishers
        columns:
          est: date
          publisher_id: integer
          active: boolean
          notes: text
          notable_games_published: text
          publisher: text
          headquarters: text
  - name: DB2
    host: arkaid-postgres.crcw0q6uux8e.ap-south-1.rds.amazonaws.com
    port: "5432"
    dbname: postgres
    username: postgres
    password: postgres
    tables:
      - name: content_creators
        columns:
          revenue: double precision
          average_views: integer
          country: text
          id: text
          primary_game: text
          type_of_content: text
          name: text
      - name: steam_games
        columns:
          price: double precision
          achievements: integer
          average_hours_played: double precision
          dlc_count: integer
          release_date: date
          about_the_game: text
          supported_languages: text
          full_audio_languages: text
          reviews: text
          header_image: text
          website: text
          support_url: text
          support_email: text
          windows: text
          mac: text
          linux: text
          developers: text
          publishers: text
          categories: text
          genres: text
          tags: text
          screenshots: text
          id: text
          movies: text
          name: text
          estimated_owners: text
          peak_ccu: text
          age_rating: text
      - name: steam_players
        columns:
          age: integer
          dob: date
          total_hrs_played: double precision
          avg_rating_given: double precision
          id: text
          library: text
          favorites: text
          payment_method: text
          country: text
          phone: text
          name: text
          username: text
          email: text
      - name: modders
        columns:
          id: text
          name: text
          type_of_mod: text
          country: text
          primary_game: text
